branch-defaults:
  master:
    environment: prod
deploy:
  artifact: java_webapp/target/java-webapp-1.5.jar
global:
  application_name: my-maven-app
  default_ec2_keyname: GovCloud-east
  default_region: us-gov-east-1
  instance_profile: null
  profile: null
  sc: git  